Return-Path: <linux-kbuild-owner@vger.kernel.org>
X-Original-To: lists+linux-kbuild@lfdr.de
Delivered-To: lists+linux-kbuild@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id 681053AE455
	for <lists+linux-kbuild@lfdr.de>; Mon, 21 Jun 2021 09:43:27 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S229888AbhFUHpj (ORCPT <rfc822;lists+linux-kbuild@lfdr.de>);
        Mon, 21 Jun 2021 03:45:39 -0400
Received: from mail-vs1-f48.google.com ([209.85.217.48]:37679 "EHLO
        mail-vs1-f48.google.com" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S229641AbhFUHpj (ORCPT
        <rfc822;linux-kbuild@vger.kernel.org>);
        Mon, 21 Jun 2021 03:45:39 -0400
Received: by mail-vs1-f48.google.com with SMTP id x12so1589090vsp.4
        for <linux-kbuild@vger.kernel.org>; Mon, 21 Jun 2021 00:43:25 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:references:in-reply-to:from:date
         :message-id:subject:to:cc;
        bh=x50V1kzcfHyNEcpfWv8+hGEMw9o1MfVMxH++Z/5oWfE=;
        b=XI3ZckhQB9WkiqxYt5e5+K58QSQWI/I1mP4v6pSJpes7UtIYbUGD5fvqccRlBcf1yP
         i/zi8f5gSUUmOz0P8vE4TesWPzoFL194FALKX3nl/h9owxBvabYy9R9eCrsWDMIkpV1u
         EzSpFDDuWmcRoVUvcaVBLjBu9wSw+0bQcThEedIEzWoXiL+WeBjWkhqMXALDiWMBkqEv
         5md4SsyNI46LG6oCanthrCcERLNKK+tpi1BzUePyAs3HHasB9CB0eP79PBzP1NUDyk2t
         8tJZtOcoJ3ArwCZ0NjkT8clFEDrZ3X11d0KhKqfafJcCBTi3bx5b62CH8WiLTIwyvDQs
         w1fQ==
X-Gm-Message-State: AOAM532xjbnzUz92PebAKKuJ4z/fOCBA5qUdUzPO10MMVPWIO5f2M2a6
        mH3PC/ml8Q/QfCOwUer+5wWyzl8OgGha8VycxcpWUoP7UNA=
X-Google-Smtp-Source: ABdhPJyCZb9cG6thf4Kt84Ot5wy1/AFUtyxxFG5mVGIZUEDysOU/5P1p1ZzhXW3YqVhV1g7UeEe10zj5GuxbBcTt4fQ=
X-Received: by 2002:a05:6102:c4c:: with SMTP id y12mr16066971vss.18.1624261405233;
 Mon, 21 Jun 2021 00:43:25 -0700 (PDT)
MIME-Version: 1.0
References: <162414828517.22205.15691327042917921585.sendpatchset@octo>
In-Reply-To: <162414828517.22205.15691327042917921585.sendpatchset@octo>
From:   Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Mon, 21 Jun 2021 09:43:14 +0200
Message-ID: <CAMuHMdWKvvohL9qVtwLxaFvxK-+o5tGu7Ap+Nv-8+RPiHuUypg@mail.gmail.com>
Subject: Re: [PATCH] arm64: clean up vdso and vdso32 files
To:     Magnus Damm <damm@opensource.se>
Cc:     Linux ARM <linux-arm-kernel@lists.infradead.org>,
        Catalin Marinas <catalin.marinas@arm.com>,
        Will Deacon <will@kernel.org>,
        Masahiro Yamada <masahiroy@kernel.org>,
        linux-kbuild <linux-kbuild@vger.kernel.org>
Content-Type: text/plain; charset="UTF-8"
Precedence: bulk
List-ID: <linux-kbuild.vger.kernel.org>
X-Mailing-List: linux-kbuild@vger.kernel.org

CC Yamada-san and kbuild

On Sun, Jun 20, 2021 at 2:57 AM Magnus Damm <damm@opensource.se> wrote:
> From: Magnus Damm <damm+renesas@opensource.se>
>
> Adjust the Makefile to remove vdso and vdso32 files during distclean.
>
> The following vdso files get generated by the defconfig as of v5.13-rc5:
>  arch/arm64/kernel/vdso/vdso.lds
>  arch/arm64/kernel/vdso/vdso.so
>  arch/arm64/kernel/vdso/vdso.so.dbg
>
> Signed-off-by: Magnus Damm <damm+renesas@opensource.se>
> ---
>
>  arch/arm64/Makefile |    3 +++
>  1 file changed, 3 insertions(+)
>
> --- 0001/arch/arm64/Makefile
> +++ work/arch/arm64/Makefile    2021-06-19 18:45:17.718559303 +0900
> @@ -181,6 +181,9 @@ archprepare:
>  # We use MRPROPER_FILES and CLEAN_FILES now
>  archclean:
>         $(Q)$(MAKE) $(clean)=$(boot)
> +       $(Q)$(MAKE) $(clean)=arch/arm64/kernel/vdso
> +       $(if $(CONFIG_COMPAT_VDSO), \
> +               $(Q)$(MAKE) $(clean)=arch/arm64/kernel/vdso32)
>
>  ifeq ($(KBUILD_EXTMOD),)
>  # We need to generate vdso-offsets.h before compiling certain files in kernel/.

Gr{oetje,eeting}s,

                        Geert

-- 
Geert Uytterhoeven -- There's lots of Linux beyond ia32 -- geert@linux-m68k.org

In personal conversations with technical people, I call myself a hacker. But
when I'm talking to journalists I just say "programmer" or something like that.
                                -- Linus Torvalds
